version: '3'

services:
  db:
    container_name: ${MONGO_NAME}
    image: mongo
    volumes:
      - poke-vol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"  # Asegúrate de exponer el puerto 27017

  mongo-express:
    depends_on:
      - db
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017/
    ports:
      - 8080:8081
    restart: always

volumes:
  poke-vol:
    external: false